import type { MetricDef } from './index'

export const ACQUISITION_METRICS: MetricDef[] = [
  {
    key: 'acq.sessions',
    owner: 'admin',
    unit: 'count',
    grain: 'daily',
    description: 'Sessionized page_viewed (30-min inactivity cut), marketing + product app.',
    version: 1,
    domain: 'acquisition',
  },
  {
    key: 'acq.visitors',
    owner: 'admin',
    unit: 'count',
    grain: 'daily',
    description: 'Unique visitors (distinct anonymous_id) across marketing + product app.',
    version: 1,
    domain: 'acquisition',
  },
  {
    key: 'acq.channel_share',
    owner: 'admin',
    unit: 'pct',
    grain: 'daily',
    description: 'Sessions per channel divided by total sessions.',
    version: 1,
    domain: 'acquisition',
  },
  {
    key: 'acq.landing_cvr',
    owner: 'admin',
    unit: 'pct',
    grain: 'daily',
    description: 'Signups attributed to landing page ÷ unique visitors (first-touch, 30-day).',
    version: 1,
    domain: 'acquisition',
  },
  {
    key: 'acq.signup_cvr',
    owner: 'admin',
    unit: 'pct',
    grain: 'daily',
    description: 'user_signed_up ÷ unique visitors.',
    version: 1,
    domain: 'acquisition',
  },
  {
    key: 'acq.signups',
    owner: 'admin',
    unit: 'count',
    grain: 'daily',
    description: 'Count of user_signed_up events, dims: channel, campaign.',
    version: 1,
    domain: 'acquisition',
  },
  {
    key: 'acq.trial_rate',
    owner: 'admin',
    unit: 'pct',
    grain: 'weekly',
    description: 'trial_started ÷ user_signed_up, weekly cohort.',
    version: 1,
    domain: 'acquisition',
  },
  {
    key: 'acq.cac',
    owner: 'admin',
    unit: 'cents',
    grain: 'monthly',
    description: 'Media CAC: spend ÷ new paying accounts; channel-decision metric.',
    version: 1,
    domain: 'acquisition',
  },
  {
    key: 'acq.score_funnel',
    owner: 'admin',
    unit: 'pct',
    grain: 'weekly',
    description: 'Free-score lead-magnet funnel conversion.',
    version: 1,
    domain: 'acquisition',
  },
  {
    key: 'acq.cac_ratio',
    owner: 'owner',
    unit: 'ratio',
    grain: 'monthly',
    description: 'Total S&M expense ÷ new-customer ARR added (CAC ratio).',
    version: 1,
    domain: 'acquisition',
    benchmark: {
      value: 2.0,
      label: 'CAC ratio 2.00x median — Benchmarkit/Pavilion, CY-2024',
      source: 'Benchmarkit/Pavilion 2025',
      vintage: 'CY-2024',
      confidence: 'high',
    },
  },
  {
    key: 'acq.ai_signups',
    owner: 'admin',
    unit: 'count',
    grain: 'daily',
    description: 'user_signed_up where first-touch referrer_class=ai_assistant.',
    version: 1,
    domain: 'acquisition',
  },
  {
    key: 'acq.campaign',
    owner: 'admin',
    unit: 'count',
    grain: 'daily',
    description: 'Sessions/signups/conversion/CAC by utm_source/medium/campaign.',
    version: 1,
    domain: 'acquisition',
  },
]
