import type { MetricDef } from './index'

export const ENGAGEMENT_METRICS: MetricDef[] = [
  {
    key: 'eng.dau',
    owner: 'admin',
    unit: 'count',
    grain: 'daily',
    description: 'Distinct user_id with ≥1 allowlist event in day window.',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.wau',
    owner: 'admin',
    unit: 'count',
    grain: 'weekly',
    description: 'Distinct user_id with ≥1 allowlist event in trailing 7d.',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.mau',
    owner: 'admin',
    unit: 'count',
    grain: 'monthly',
    description: 'Distinct user_id with ≥1 allowlist event in trailing 28d.',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.acct_dau',
    owner: 'admin',
    unit: 'count',
    grain: 'daily',
    description: 'Distinct account_id with ≥1 value-active user.',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.acct_wau',
    owner: 'admin',
    unit: 'count',
    grain: 'weekly',
    description: 'Distinct account_id with ≥1 value-active user in trailing 7d.',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.acct_mau',
    owner: 'admin',
    unit: 'count',
    grain: 'monthly',
    description: 'Distinct account_id with ≥1 value-active user in trailing 28d.',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.stick_wm',
    owner: 'admin',
    unit: 'pct',
    grain: 'monthly',
    description: 'WAU ÷ MAU (primary for Clovion — weekly cadence product).',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.stick_dm',
    owner: 'admin',
    unit: 'pct',
    grain: 'monthly',
    description: 'DAU ÷ MAU (secondary).',
    version: 1,
    domain: 'engagement',
    benchmark: {
      value: 31,
      label: 'B2B median 31% — Mixpanel State of Digital Analytics, May 2026',
      source: 'Mixpanel SoDA 2026',
      vintage: '2026-05',
      confidence: 'medium',
    },
  },
  {
    key: 'eng.l7',
    owner: 'admin',
    unit: 'count',
    grain: 'weekly',
    description: 'Histogram: % of MAU active exactly N days of trailing 7.',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.l28',
    owner: 'admin',
    unit: 'count',
    grain: 'monthly',
    description: 'Histogram: % of MAU active exactly N days of trailing 28.',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.feat_adopt',
    owner: 'admin',
    unit: 'pct',
    grain: 'monthly',
    description: '% of MAU accounts using feature key in 28d.',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.feat_freq',
    owner: 'admin',
    unit: 'count',
    grain: 'monthly',
    description: 'Median uses per adopting account, 28d.',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.session_depth',
    owner: 'admin',
    unit: 'count',
    grain: 'daily',
    description: 'Median events/session and median session duration.',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.seat_util',
    owner: 'admin',
    unit: 'pct',
    grain: 'monthly',
    description: 'Value-active users 28d ÷ provisioned seats, per account.',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.quota_util',
    owner: 'admin',
    unit: 'pct',
    grain: 'daily',
    description: 'Prompt-runs consumed ÷ plan quota, per account.',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.api',
    owner: 'admin',
    unit: 'count',
    grain: 'daily',
    description: 'API request volume and distinct accounts using.',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.mcp',
    owner: 'admin',
    unit: 'count',
    grain: 'daily',
    description: 'MCP request volume and distinct accounts using.',
    version: 1,
    domain: 'engagement',
  },
  {
    key: 'eng.visits',
    owner: 'admin',
    unit: 'count',
    grain: 'daily',
    description: 'Pageview-only presence (non-headline).',
    version: 1,
    domain: 'engagement',
  },
]
