import type { MetricDef } from './index'

export const GOVERNANCE_METRICS: MetricDef[] = [
  {
    key: 'gov.admin_actions',
    owner: 'owner',
    unit: 'count',
    grain: 'daily',
    description: 'Count by type/actor/status from admin_actions.',
    version: 1,
    domain: 'governance',
  },
  {
    key: 'gov.impersonations',
    owner: 'owner',
    unit: 'count',
    grain: 'daily',
    description: 'Count, median duration, approval latency, % read-only.',
    version: 1,
    domain: 'governance',
  },
  {
    key: 'gov.audit_chain',
    owner: 'owner',
    unit: 'count',
    grain: 'weekly',
    description: 'Weekly hash-chain verification pass/fail.',
    version: 1,
    domain: 'governance',
  },
  {
    key: 'gov.auth_fail',
    owner: 'owner',
    unit: 'count',
    grain: 'hourly',
    description: 'Auth.js rejected sign-ins.',
    version: 1,
    domain: 'governance',
  },
  {
    key: 'gov.pii_reveals',
    owner: 'owner',
    unit: 'count',
    grain: 'daily',
    description: 'pii.reveal permission uses, by actor.',
    version: 1,
    domain: 'governance',
  },
  {
    key: 'gov.dsr',
    owner: 'owner',
    unit: 'count',
    grain: 'daily',
    description: 'Open GDPR DSRs, days-to-complete, deadline proximity.',
    version: 1,
    domain: 'governance',
  },
  {
    key: 'gov.dead_letter',
    owner: 'engineer',
    unit: 'count',
    grain: 'hourly',
    description: 'Ingest dead-letter depth.',
    version: 1,
    domain: 'governance',
  },
  {
    key: 'gov.unregistered',
    owner: 'engineer',
    unit: 'count',
    grain: 'daily',
    description: 'Unregistered event names seen.',
    version: 1,
    domain: 'governance',
  },
  {
    key: 'gov.recon_open',
    owner: 'owner',
    unit: 'count',
    grain: 'daily',
    description: 'Open reconciliation_issues.',
    version: 1,
    domain: 'governance',
  },
]
