import type { MetricDef } from './index'

export const PERFORMANCE_METRICS: MetricDef[] = [
  {
    key: 'perf.lcp',
    owner: 'engineer',
    unit: 'ms',
    grain: 'daily',
    description: 'Core Web Vitals LCP p75 per page group.',
    version: 1,
    domain: 'performance',
    benchmark: {
      value: 2500,
      label: 'LCP ≤ 2.5s at p75 — web.dev documented',
      source: 'web.dev',
      vintage: 'current',
      confidence: 'high',
    },
  },
  {
    key: 'perf.inp',
    owner: 'engineer',
    unit: 'ms',
    grain: 'daily',
    description: 'Core Web Vitals INP p75.',
    version: 1,
    domain: 'performance',
    benchmark: {
      value: 200,
      label: 'INP ≤ 200ms at p75 — web.dev',
      source: 'web.dev',
      vintage: 'current',
      confidence: 'high',
    },
  },
  {
    key: 'perf.cls',
    owner: 'engineer',
    unit: 'score',
    grain: 'daily',
    description: 'Core Web Vitals CLS p75.',
    version: 1,
    domain: 'performance',
    benchmark: {
      value: 0.1,
      label: 'CLS ≤ 0.1 at p75 — web.dev',
      source: 'web.dev',
      vintage: 'current',
      confidence: 'high',
    },
  },
  {
    key: 'perf.api_p50',
    owner: 'engineer',
    unit: 'ms',
    grain: 'hourly',
    description: 'API latency p50.',
    version: 1,
    domain: 'performance',
  },
  {
    key: 'perf.api_p95',
    owner: 'engineer',
    unit: 'ms',
    grain: 'hourly',
    description: 'API latency p95.',
    version: 1,
    domain: 'performance',
  },
  {
    key: 'perf.api_p99',
    owner: 'engineer',
    unit: 'ms',
    grain: 'hourly',
    description: 'API latency p99.',
    version: 1,
    domain: 'performance',
  },
  {
    key: 'perf.error_rate',
    owner: 'engineer',
    unit: 'pct',
    grain: 'hourly',
    description: 'Error rate (non-5xx ÷ total) — SRE ratio SLI.',
    version: 1,
    domain: 'performance',
  },
  {
    key: 'perf.slo_availability',
    owner: 'engineer',
    unit: 'pct',
    grain: 'daily',
    description: 'Availability SLO; 28-day rolling.',
    version: 1,
    domain: 'performance',
  },
  {
    key: 'perf.slo_latency',
    owner: 'engineer',
    unit: 'pct',
    grain: 'daily',
    description: 'Latency SLO compliance; multi-percentile.',
    version: 1,
    domain: 'performance',
  },
  {
    key: 'perf.uptime',
    owner: 'engineer',
    unit: 'pct',
    grain: 'daily',
    description: 'Better Stack uptime monitors 7/30d.',
    version: 1,
    domain: 'performance',
  },
  {
    key: 'perf.release',
    owner: 'engineer',
    unit: 'pct',
    grain: 'daily',
    description: 'Crash-free sessions %, errors per release.',
    version: 1,
    domain: 'performance',
  },
  {
    key: 'perf.queue_depth',
    owner: 'engineer',
    unit: 'count',
    grain: 'realtime',
    description: 'Worker queue depth (jobs waiting).',
    version: 1,
    domain: 'performance',
  },
  {
    key: 'perf.queue_age',
    owner: 'engineer',
    unit: 'ms',
    grain: 'realtime',
    description: 'Oldest-job age in queue.',
    version: 1,
    domain: 'performance',
  },
  {
    key: 'perf.queue_fail',
    owner: 'engineer',
    unit: 'count',
    grain: 'daily',
    description: 'Queue failures 24h.',
    version: 1,
    domain: 'performance',
  },
  {
    key: 'perf.saturation',
    owner: 'engineer',
    unit: 'pct',
    grain: 'hourly',
    description: 'DB CPU %, storage %, connection-pool utilization.',
    version: 1,
    domain: 'performance',
  },
]
