import type { MetricDef } from './index'

export const PIPELINE_METRICS: MetricDef[] = [
  {
    key: 'ai.run_success',
    owner: 'engineer',
    unit: 'pct',
    grain: 'hourly',
    description: 'Successful ÷ scheduled runs (skipped excluded), per engine.',
    version: 1,
    domain: 'pipeline',
  },
  {
    key: 'ai.fail_class',
    owner: 'engineer',
    unit: 'pct',
    grain: 'daily',
    description: 'Failure class share (scrape_block/auth/rate_limit/parse/llm_error/timeout/infra).',
    version: 1,
    domain: 'pipeline',
  },
  {
    key: 'ai.freshness',
    owner: 'engineer',
    unit: 'pct',
    grain: 'hourly',
    description: '% of active prompts with successful run ≤ 26h.',
    version: 1,
    domain: 'pipeline',
  },
  {
    key: 'ai.run_latency',
    owner: 'engineer',
    unit: 'ms',
    grain: 'hourly',
    description: 'p50/p95 per engine from pipeline_runs.latency_ms.',
    version: 1,
    domain: 'pipeline',
  },
  {
    key: 'ai.retries',
    owner: 'engineer',
    unit: 'count',
    grain: 'daily',
    description: 'Mean retries per completed run, per engine.',
    version: 1,
    domain: 'pipeline',
  },
  {
    key: 'ai.tokens',
    owner: 'engineer',
    unit: 'count',
    grain: 'daily',
    description: 'Σ tokens from llm_cost_ledger by provider/model/engine/feature/account/day.',
    version: 1,
    domain: 'pipeline',
  },
  {
    key: 'ai.spend',
    owner: 'engineer',
    unit: 'microcents',
    grain: 'daily',
    description: 'Σ cost_usd_microcents from llm_cost_ledger; budget = ops_settings.',
    version: 1,
    domain: 'pipeline',
  },
  {
    key: 'ai.free_burn',
    owner: 'owner',
    unit: 'microcents',
    grain: 'daily',
    description: 'Σ ledger cost of plan_tier=free accounts.',
    version: 1,
    domain: 'pipeline',
  },
  {
    key: 'ai.cost_per_run',
    owner: 'engineer',
    unit: 'microcents',
    grain: 'daily',
    description: 'Spend ÷ completed runs, per engine.',
    version: 1,
    domain: 'pipeline',
  },
  {
    key: 'ai.acct_cost',
    owner: 'owner',
    unit: 'microcents',
    grain: 'monthly',
    description: 'Σ ledger by account, 30d.',
    version: 1,
    domain: 'pipeline',
  },
  {
    key: 'ai.margin',
    owner: 'owner',
    unit: 'cents',
    grain: 'daily',
    description: 'Daily-ized MRR − attributable LLM cost − infra constant − Stripe fees.',
    version: 1,
    domain: 'pipeline',
  },
  {
    key: 'ai.cost_source',
    owner: 'engineer',
    unit: 'pct',
    grain: 'daily',
    description: 'Share of ledger rows with provider-reported cost vs price-book-inferred.',
    version: 1,
    domain: 'pipeline',
  },
  {
    key: 'ai.platform_spend',
    owner: 'engineer',
    unit: 'pct',
    grain: 'daily',
    description: '__platform__ account spend ÷ total. Target < 3%.',
    version: 1,
    domain: 'pipeline',
  },
  {
    key: 'ai.scraper',
    owner: 'engineer',
    unit: 'count',
    grain: 'realtime',
    description: 'Latest scraper_health_changed state per engine.',
    version: 1,
    domain: 'pipeline',
  },
  {
    key: 'ai.skipped',
    owner: 'engineer',
    unit: 'count',
    grain: 'daily',
    description: 'status=skipped counts by cause (quota, kill_switch).',
    version: 1,
    domain: 'pipeline',
  },
]
