import type { MetricDef } from './index'

export const RETENTION_METRICS: MetricDef[] = [
  {
    key: 'ret.logo_churn',
    owner: 'owner',
    unit: 'pct',
    grain: 'monthly',
    description: 'Accounts churned in month ÷ paying accounts at month start.',
    version: 1,
    domain: 'retention',
  },
  {
    key: 'ret.mrr_churn',
    owner: 'owner',
    unit: 'pct',
    grain: 'monthly',
    description: 'Churned MRR ÷ MRR at month start.',
    version: 1,
    domain: 'retention',
  },
  {
    key: 'ret.grr',
    owner: 'owner',
    unit: 'pct',
    grain: 'monthly',
    description: '(Start MRR − churn − contraction) ÷ start MRR, monthly cohort.',
    version: 1,
    domain: 'retention',
    benchmark: {
      value: 88,
      label: 'GRR 88% median — Benchmarkit, FY-2024',
      source: 'Benchmarkit 2025',
      vintage: 'FY-2024',
      confidence: 'high',
    },
  },
  {
    key: 'ret.nrr_ttm',
    owner: 'owner',
    unit: 'pct',
    grain: 'monthly',
    description: 'Trailing-12-month NRR — MRR today from cohort that was paying 12mo ago.',
    version: 1,
    domain: 'retention',
    anchor: true,
    benchmark: {
      value: 101,
      label: 'NRR 101% blended — Benchmarkit/Pavilion, CY-2024',
      source: 'Benchmarkit/Pavilion 2025',
      vintage: 'CY-2024',
      confidence: 'high',
    },
  },
  {
    key: 'ret.nrr_m',
    owner: 'owner',
    unit: 'pct',
    grain: 'monthly',
    description: 'Monthly NRR (diagnostic — no benchmark label).',
    version: 1,
    domain: 'retention',
  },
  {
    key: 'ret.cohort',
    owner: 'admin',
    unit: 'pct',
    grain: 'cohort',
    description: 'Cohort retention heatmap: months 0-12, logo % and revenue %.',
    version: 1,
    domain: 'retention',
  },
  {
    key: 'ret.churn_split',
    owner: 'owner',
    unit: 'pct',
    grain: 'monthly',
    description: 'Churned accounts split by reason_code vs dunning-exhaustion.',
    version: 1,
    domain: 'retention',
  },
  {
    key: 'ret.react',
    owner: 'owner',
    unit: 'pct',
    grain: 'monthly',
    description: 'Reactivated MRR ÷ churned MRR trailing 90d.',
    version: 1,
    domain: 'retention',
  },
  {
    key: 'ret.reasons',
    owner: 'owner',
    unit: 'pct',
    grain: 'monthly',
    description: 'Distribution of reason_code on cancellations.',
    version: 1,
    domain: 'retention',
  },
  {
    key: 'ret.at_risk',
    owner: 'support',
    unit: 'score',
    grain: 'daily',
    description: 'Heuristic at-risk score per account; sorted by MRR at risk.',
    version: 1,
    domain: 'retention',
  },
  {
    key: 'ret.expansion_ready',
    owner: 'admin',
    unit: 'count',
    grain: 'daily',
    description: 'Accounts with seat/quota utilization > 80% suggesting expansion.',
    version: 1,
    domain: 'retention',
  },
]
