import type { MetricDef } from './index'

export const REVENUE_METRICS: MetricDef[] = [
  {
    key: 'rev.mrr',
    owner: 'owner',
    unit: 'cents',
    grain: 'daily',
    description: 'Sum of normalized active subscription items.',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.arr',
    owner: 'owner',
    unit: 'cents',
    grain: 'daily',
    description: 'MRR × 12.',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.mrr_new',
    owner: 'owner',
    unit: 'cents',
    grain: 'monthly',
    description: 'New MRR from snapshot-diff (new subscriptions).',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.mrr_expansion',
    owner: 'owner',
    unit: 'cents',
    grain: 'monthly',
    description: 'Expansion MRR from plan/quantity upgrades.',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.mrr_contraction',
    owner: 'owner',
    unit: 'cents',
    grain: 'monthly',
    description: 'Contraction MRR from plan/quantity downgrades.',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.mrr_churned',
    owner: 'owner',
    unit: 'cents',
    grain: 'monthly',
    description: 'Churned MRR from cancellations.',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.mrr_reactivation',
    owner: 'owner',
    unit: 'cents',
    grain: 'monthly',
    description: 'Reactivated MRR (churn returning within 12 months).',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.mrr_discount_change',
    owner: 'owner',
    unit: 'cents',
    grain: 'monthly',
    description: 'Discount-only changes — excluded from expansion/contraction in NRR/GRR.',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.free_paid_cvr',
    owner: 'owner',
    unit: 'pct',
    grain: 'monthly',
    description: 'Paying within 30/90d ÷ free-account cohort.',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.expansion_share',
    owner: 'owner',
    unit: 'pct',
    grain: 'monthly',
    description: 'Expansion ARR ÷ (new + expansion ARR).',
    version: 1,
    domain: 'revenue',
    benchmark: {
      value: 40,
      label: 'Expansion share 40% median — Pavilion/Benchmarkit, CY-2024',
      source: 'Benchmarkit/Pavilion 2025',
      vintage: 'CY-2024',
      confidence: 'high',
    },
  },
  {
    key: 'rev.arpa',
    owner: 'owner',
    unit: 'cents',
    grain: 'monthly',
    description: 'MRR ÷ paying accounts; median and p90 by tier.',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.trial_cvr',
    owner: 'owner',
    unit: 'pct',
    grain: 'monthly',
    description: 'Paying within 14/30d of trial start ÷ trial cohort.',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.ttc',
    owner: 'owner',
    unit: 'duration_h',
    grain: 'monthly',
    description: 'Days trial start → first payment; distribution.',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.ltv',
    owner: 'owner',
    unit: 'cents',
    grain: 'monthly',
    description: 'ARPA × GM% ÷ max(monthly revenue churn, 0.5% floor), capped 36×.',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.ltv_cac',
    owner: 'owner',
    unit: 'ratio',
    grain: 'monthly',
    description: 'LTV ÷ blended CAC. Convention: > 3:1 healthy (rule of thumb).',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.cac_payback',
    owner: 'owner',
    unit: 'count',
    grain: 'monthly',
    description: 'Fully-loaded CAC ÷ (ARPA × GM%) in months.',
    version: 1,
    domain: 'revenue',
    anchor: true,
    benchmark: {
      value: 24,
      label: 'CAC payback median 24mo — High Alpha 2025',
      source: 'High Alpha × Growth Unhinged 2025',
      vintage: '2025-09',
      confidence: 'high',
    },
  },
  {
    key: 'rev.quick',
    owner: 'owner',
    unit: 'ratio',
    grain: 'monthly',
    description: '(New + expansion MRR) ÷ (churned + contraction MRR).',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.rule40',
    owner: 'owner',
    unit: 'pct',
    grain: 'monthly',
    description: 'YoY ARR growth % + FCF margin %.',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.dunning_fail',
    owner: 'owner',
    unit: 'pct',
    grain: 'monthly',
    description: 'Failed invoice payments ÷ invoice attempts.',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.dunning_recovery',
    owner: 'owner',
    unit: 'pct',
    grain: 'monthly',
    description: 'Recovered MRR ÷ MRR that entered dunning trailing 60d.',
    version: 1,
    domain: 'revenue',
  },
  {
    key: 'rev.delinquent',
    owner: 'owner',
    unit: 'cents',
    grain: 'daily',
    description: 'Sum MRR of accounts in past_due / unpaid status.',
    version: 1,
    domain: 'revenue',
  },
]
